### ISSUE TITLE
Fails to expand Windows paths with brackets

### ISSUE THREAD

**Issue by naturalethic** [micromatch/braces#16]
```
> const p2 = 'C:\\Users\\foo\\Workspace\\project\\routes\\[locale]'
> braces.expand(p2)
Error: no parsers registered for: "]"
    at parse (C:\Users\foo\Workspace\project\node_modules\snapdragon\lib\parser.js:475:15)
```

**Comment by jonschlinkert** [comment]
This is correct, you escaped the first brace, `\\[` so the second one is a parsing error. Backticks are used for escaping in glob patterns. All path separators must be forward slashes. This isn't our rule, it's the rule for all globbing libraries.

**Comment by naturalethic** [comment]
Those aren't escaped brackets, they're escaped backslashes for a windows path.

**Comment by naturalethic** [comment]
> This isn't our rule, it's the rule for all globbing libraries.

If that is true, perhaps this bug belongs to chokidar, we'll see what they say on their ticket.

**Comment by jonschlinkert** [comment]
> To be clear, chokidar is broken on Windows due to this libraries inability to recognize this condition.

To be clear, `\\[foo]` is an invalid bracket expression.  This topic has been exhaustively discussed on many issues on several projects. If chokidar is creating the glob pattern, then that is a bug in chokidar, since glob patterns should only use backslashes for escaping a value. Given that `\\` in a string is converted to `\` in a regex, it is actually escaping `[`, not the backslash. I would be happy to discuss and help with creating a solution on chokidar. But it is not a bug in this library.

**Comment by jonschlinkert** [comment]
> If that is true, perhaps this bug belongs to chokidar, we'll see what they say on their ticket.

I'd be happy to help there.

**Comment by naturalethic** [comment]
Yep, ok sorry, i had deleted that line in my comment, I'm not fully awake yet.

**Comment by jonschlinkert** [comment]
> Yep, ok sorry, i had deleted that line in my comment, I'm not fully awake yet.

no that's ok, I didn't mean to sound harsh. it happens

**Comment by sorentycho** [comment]
Definitely looks like this is a chokidar bug: https://github.com/paulmillr/chokidar/issues/699#issuecomment-437293197
